# Generated by Django 5.2.4 on 2025-08-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='amenities',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='num_bathrooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='listing',
            name='num_bedrooms',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
