# Generated by Django 5.2.4 on 2025-08-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_booking_total_amount_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('Studio', 'Studio'), ('1 Bedroom', '1BR'), ('2 Bedroom', '2BR'), ('3 Bedroom', '3BR'), ('Penthouse', 'Penthouse'), ('Loft', 'Loft')], default='Studio', max_length=50),
        ),
    ]
