# Generated by Django 5.2.4 on 2025-08-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('Studio', 'Studio'), ('1BR', '1 Bedroom'), ('2BR', '2 Bedroom'), ('3BR', '3 Bedroom'), ('Penthouse', 'Penthouse'), ('Loft', 'Loft')], default='Studio', max_length=50),
        ),
    ]
